// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddInterfaceVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddInterfaceVSIXPackageString = "b77eddb8-0283-454d-8620-5e3efd435a80";
        public static Guid guidAddInterfaceVSIXPackage = new Guid(guidAddInterfaceVSIXPackageString);

        public const string guidAddInterfaceVSIXPackageCmdSetString = "3f8194bf-dd7d-49f1-bbbe-430440c16c09";
        public static Guid guidAddInterfaceVSIXPackageCmdSet = new Guid(guidAddInterfaceVSIXPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemToolWindowCommandId = 0x0100;
    }
}